services:
  php72:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_72
    restart: unless-stopped
    volumes:
      - /root/www:/var/www/html
    networks:
      - web

networks:
  web:
    external: true
